---
- name: Créer une structure de dossiers et fichiers
  hosts: local
  vars:
    base_dir: ./test
    dossier_noms:
      - docs
      - scripts
      - notes
  tasks:
    - name: Créer le dossier principal
      file:
        path: "{{ base_dir }}"
        state: directory
        mode: '0755'
    - name: Créer les sous-dossiers
      file:
        path: "{{ base_dir }}/{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ dossier_noms }}"
    - name: Créer un fichier README dans chaque dossier
      copy:
        dest: "{{ base_dir }}/{{ item }}/README.txt"
        content: "Ce dossier {{ item }} a été créé automatiquement."
        mode: '0644'
      with_items: "{{ dossier_noms }}"
